### ISSUE TITLE
Build Linux versions against libs that work in Centos 6

### ISSUE THREAD

**Issue by bhouston** [Exocortex/ExocortexCrate#12]
According to:

http://studiosysadmins.com/board/threadview/5235/

Linux versions only run on Centos 7 and newer.  Probably because the Maya versions were compiled against Fedora 14, while Centos 6 was forked from Fedora 12 according to here: http://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux

**Comment by renaudll** [comment]
I've been able to build it in CentOS 6.6.
Everything went well after building boost using the instructions provided in BUILDING_BOOST.md, however I had to rename the "cxx-flags=-fPIC" to "cxxflags=-fPIC". 
Do you want me to send you the compiled boost lib to include them in Libraries.XXXXXXXX.XX?

**Comment by bhouston** [comment]
Yes, please share the binaries with me so I can redistribute. :)

**Comment by caron** [comment]
We are switching to Linux from Windows and are using CentOS 6.6, when can we get access to these pre-built binaries?

**Comment by renaudll** [comment]
While we wait for an official download link I can still send you the binaries I've built via email. 
Just email me at rlessard[at]squeezestudio[dot]com and specify the version you need.
Cheers!

**Comment by bhouston** [comment]
I've uploaded the Libraries to include @renaudll boost.  They are linked to by the latest code checked into master.
