### ISSUE TITLE
Compile Error with VS2012

### ISSUE THREAD

**Issue by simoneves** [Exocortex/ExocortexCrate#20]
Several errors compiling Shared/CommonUtils/CommonImports.cpp due to missing member "prefix" of IJobStringParser class defined in CommonImports.h. Adding std::string prefix to the class makes it build, although I haven't tried running it yet.

**Comment by bhouston** [comment]
Fixed in https://github.com/Exocortex/ExocortexCrate/pull/25

**Comment by ulrikjorgensen** [comment]
Thanks.
Strangely enough I had this running all the time.
Could be the build setups(halt on warnings etc).

**Comment by bhouston** [comment]
The weird thing is that I didnt get this either as a showstopper bug.  I of course compiled with VS2012 for the releases.  But it affected more than a couple people. so merging the fix makes sense.
