### ISSUE TITLE
Maya Windows Compiler Versions

### ISSUE THREAD

**Issue by simoneves** [Exocortex/ExocortexCrate#22]
I am wondering if the MSVCxx logic for the Maya sub-projects in the master CMake file is correct?

Surely Maya 2010-2012 should only be built if MSVC9, Maya 2013 & 2014 if MSVC10, and 2015 if MSVC11?

**Comment by bhouston** [comment]
This is what we ship and I understand it works.  Often it is possible to use older compilers are compatible with tools compiled with newer versions.  Thus if we compile with an older compiler than what maya uses, we are still compatible.
