### ISSUE TITLE
Inconsistent indentation levels

### ISSUE THREAD

**Issue by AWhetter** [Exocortex/ExocortexCrate#40]
The code style is inconsistent between files and also in files.

For most things this isn't a big deal but the main problem is the indentation is inconsistent (eg https://github.com/Exocortex/ExocortexCrate/blob/31c808272cfb25e74eb1a79151eebce41718701d/Maya/AlembicWriteJob.cpp). As a new contributor it would make the code a lot easier to understand if an indentation level was agreed upon and than standardized in the source files.

There are other style inconsistencies like usage of brackets in if chains (eg https://github.com/Exocortex/ExocortexCrate/blob/31c808272cfb25e74eb1a79151eebce41718701d/Maya/AlembicWriteJob.cpp#L515-L566) and spacing between operators, but these are not as important for understanding the code.

**Comment by bhouston** [comment]
If you wanted to run a code cleanup tool and submit a PR, that would be okay with us.  :)

I believe the best automated source code formatting tool is http://clang.llvm.org/docs/ClangFormat.html

**Comment by AWhetter** [comment]
I have a work in progress version that looks good. I haven't tested it though, so I'll test and pull request it next week.
